version: "3"

services:
  odwebservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: od_i:latest
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    container_name: od_c
    ports:
      - "8002:8002"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
